apiVersion: v1
kind: Secret
metadata:
  name: video-streaming-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: sa
  SPRING_DATASOURCE_PASSWORD: Admin@123

  AWS_ACCESS_KEY: AKIsdfsfdsdA4IJ3O2P6MMJ5AUCD
  AWS_SECRET_KEY: Eo/x7Gasdfsf8yXI4NcOeWudA/XRKm5/TGPLBDSTmnCB5g
